import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'tr' | 'de' | 'ar';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations for all supported languages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.viewingAs': 'Viewing as:',
    'header.selectUniversity': 'Select University',
    'header.loading': 'Loading...',
    'header.turkishUniversities': 'Turkish Universities',
    'header.internationalUniversities': 'International Universities',
    'header.signOut': 'Sign Out',
    'header.language': 'Language',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.partners': 'Partners',
    'nav.mobility': 'Mobility',
    'nav.mou': 'MOU',
    'nav.partnerships': 'Partnerships',
    'nav.intelligence': 'Intelligence',
    'nav.partnerAnalytics': 'Analytics',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.activePartnerships': 'Active Partnerships',
    'dashboard.pendingMOUs': 'Pending MOUs',
    'dashboard.mobilityBalance': 'Mobility Balance',
    'dashboard.actionItems': 'Action Items',
    'dashboard.mobilityTrends': 'Mobility Trends',
    'dashboard.mouStatus': 'MOU Status',
    'dashboard.partnersByRegion': 'Partners by Region',
    'dashboard.projectsOverview': 'Projects Overview',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.marketIntelligence': 'Market Intelligence',
    
    // Profile
    'profile.title': 'University Profile',
    'profile.subtitle': 'AI-generated institutional analysis and strategic intelligence',
    'profile.healthIndex': 'Institutional Health Index',
    'profile.overallScore': 'Overall Score',
    'profile.executiveSummary': 'Executive Summary',
    'profile.strengths': 'Strengths',
    'profile.weaknesses': 'Weaknesses',
    'profile.recommendations': 'Strategic Recommendations',
    'profile.departmentROI': 'Department ROI Analysis',
    
    // Partners
    'partners.title': 'Partner Discovery',
    'partners.subtitle': 'AI-powered partner recommendations and university database',
    'partners.aiRecommended': 'AI Recommended',
    'partners.allUniversities': 'All Universities',
    'partners.search': 'Search partners...',
    'partners.allRegions': 'All Regions',
    'partners.refresh': 'Refresh',
    'partners.viewProfile': 'View Profile',
    'partners.initiateMOU': 'Initiate MOU',
    'partners.matchScore': 'Match Score',
    
    // Mobility
    'mobility.title': 'Student Mobility Management',
    'mobility.subtitle': 'Track student mobility, manage applications, and generate learning agreements',
    'mobility.selectUniversityPrompt': 'Please select a university from the header.',
    'mobility.overview': 'Overview',
    'mobility.studentApplications': 'Student Applications',
    'mobility.learningAgreements': 'Learning Agreements',
    'mobility.dataFor': 'Mobility data for',
    'mobility.incoming': 'Incoming',
    'mobility.outgoing': 'Outgoing',
    'mobility.incomingStudents': 'Incoming Students',
    'mobility.outgoingStudents': 'Outgoing Students',
    'mobility.partnerUniversities': 'Partner Universities',
    'mobility.activePrograms': 'Active Programs',
    'mobility.programDistribution': 'Program Distribution',
    'mobility.program.erasmus': 'Erasmus+',
    'mobility.program.bilateral': 'Bilateral',
    'mobility.program.exchange': 'Exchange',
    'mobility.program.jointDegree': 'Joint Degree',
    'mobility.programType': 'Program Type',
    'mobility.allPrograms': 'All Programs',
    'mobility.direction': 'Direction',
    'mobility.allDirections': 'All Directions',
    'mobility.academicYear': 'Academic Year',
    'mobility.allYears': 'All Years',
    'mobility.filters': 'Filters:',
    'mobility.recordsTitle': 'Mobility Records',
    'mobility.noRecords': 'No mobility records found',
    'mobility.noRecordsDesc': 'Mobility data will appear here once programs are active',
    'mobility.table.partnerUniversity': 'Partner University',
    'mobility.table.program': 'Program',
    'mobility.table.direction': 'Direction',
    'mobility.table.students': 'Students',
    'mobility.table.academicYear': 'Academic Year',
    'mobility.table.status': 'Status',
    'mobility.ongoing': 'Ongoing',
    'mobility.completed': 'Completed',
    'mobility.cancelled': 'Cancelled',
    'mobility.status': 'Status',
    
    // MOU
    'mou.title': 'MOU Management',
    'mou.createNew': 'Create New MOU',
    'mou.status': 'Status',
    'mou.partner': 'Partner',
    'mou.clauses': 'Clauses',
    'mou.history': 'History',
    
    // Recruitment
    'recruitment.title': 'Recruitment',
    'recruitment.subtitle': 'International student recruitment tracking and market intelligence',
    'recruitment.selectUniversity': 'Please select a university to view recruitment data.',
    'recruitment.editNumbers': 'Edit Numbers',
    'recruitment.saved': 'Changes Saved',
    'recruitment.savedDesc': 'Recruitment data has been updated successfully.',
    'recruitment.totalStudents': 'Total Students',
    'recruitment.countries': 'Countries',
    'recruitment.acceptanceLetters': 'Acceptance Letters',
    'recruitment.registered': 'Registered',
    'recruitment.frozen': 'Frozen',
    'recruitment.transfer': 'Transfer',
    'recruitment.deleted': 'Deleted',
    'recruitment.graduated': 'Graduated',
    'recruitment.byCountry': 'By Country',
    'recruitment.byAgency': 'By Agency',
    'recruitment.marketIntelligence': 'Market Intelligence',
    'recruitment.studentsByCountry': 'Students by Country',
    'recruitment.studentsByCountryDesc': 'Track student numbers across all recruitment metrics by country',
    'recruitment.studentsByAgency': 'Students by Agency',
    'recruitment.studentsByAgencyDesc': 'Track student recruitment through partner agencies',
    'recruitment.country': 'Country',
    'recruitment.agency': 'Agency',
    'recruitment.students': 'Students',
    'recruitment.mainCountries': 'Main Countries',
    'recruitment.commission': 'Commission',
    'recruitment.total': 'Total',
    'recruitment.avg': 'avg',
    'recruitment.agencies': 'agencies',
    'recruitment.analyzing': 'Analyzing...',
    'recruitment.analysisComplete': 'Analysis Complete',
    'recruitment.analysisCompleteDesc': 'Market intelligence report generated successfully.',
    'recruitment.analysisFailed': 'Failed to generate analysis',
    'recruitment.analysisError': 'Analysis Error',
    'recruitment.generatingIntelligence': 'Generating market intelligence...',
    'recruitment.totalApplications': 'Total Applications',
    'recruitment.avgConversion': 'Avg. Conversion',
    'recruitment.marketsToScale': 'Markets to Scale',
    'recruitment.marketsToPause': 'Markets to Pause',
    'recruitment.marketsToExit': 'Markets to Exit',
    
    // Market Intelligence
    'intelligence.title': 'Market Intelligence',
    'intelligence.subtitle': 'AI-powered market analysis and strategic recommendations',
    'intelligence.generateAnalysis': 'Generate Analysis',
    'intelligence.regenerate': 'Regenerate',
    'intelligence.recommendations': 'AI Recommendations',
    'intelligence.metrics': 'Market Metrics',
    'intelligence.confidence': 'Confidence',
    'intelligence.risk': 'Risk Level',
    'intelligence.keyMetrics': 'Key Metrics',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'common.generate': 'Generate',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.draft': 'Draft',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.students': 'students',
    'common.records': 'records',
    'common.unknown': 'Unknown',
  },
  tr: {
    // Header
    'header.viewingAs': 'Görüntülenen:',
    'header.selectUniversity': 'Üniversite Seçin',
    'header.loading': 'Yükleniyor...',
    'header.turkishUniversities': 'Türk Üniversiteleri',
    'header.internationalUniversities': 'Uluslararası Üniversiteler',
    'header.signOut': 'Çıkış Yap',
    'header.language': 'Dil',
    
    // Navigation
    'nav.dashboard': 'Gösterge Paneli',
    'nav.profile': 'Profil',
    'nav.partners': 'Ortaklar',
    'nav.mobility': 'Hareketlilik',
    'nav.mou': 'MOU',
    'nav.partnerships': 'Ortaklıklar',
    'nav.intelligence': 'Pazar Analizi',
    'nav.partnerAnalytics': 'Analitik',
    
    // Dashboard
    'dashboard.title': 'Gösterge Paneli',
    'dashboard.activePartnerships': 'Aktif Ortaklıklar',
    'dashboard.pendingMOUs': 'Bekleyen MOU\'lar',
    'dashboard.mobilityBalance': 'Hareketlilik Dengesi',
    'dashboard.actionItems': 'Eylem Öğeleri',
    'dashboard.mobilityTrends': 'Hareketlilik Trendleri',
    'dashboard.mouStatus': 'MOU Durumu',
    'dashboard.partnersByRegion': 'Bölgeye Göre Ortaklar',
    'dashboard.projectsOverview': 'Projeler Genel Bakış',
    'dashboard.quickActions': 'Hızlı İşlemler',
    'dashboard.marketIntelligence': 'Pazar Analizi',
    
    // Profile
    'profile.title': 'Üniversite Profili',
    'profile.subtitle': 'Yapay zeka destekli kurumsal analiz ve stratejik istihbarat',
    'profile.healthIndex': 'Kurumsal Sağlık Endeksi',
    'profile.overallScore': 'Genel Puan',
    'profile.executiveSummary': 'Yönetici Özeti',
    'profile.strengths': 'Güçlü Yönler',
    'profile.weaknesses': 'Zayıf Yönler',
    'profile.recommendations': 'Stratejik Öneriler',
    'profile.departmentROI': 'Bölüm ROI Analizi',
    
    // Partners
    'partners.title': 'Ortak Keşfi',
    'partners.subtitle': 'Yapay zeka destekli ortak önerileri ve üniversite veritabanı',
    'partners.aiRecommended': 'Yapay Zeka Önerileri',
    'partners.allUniversities': 'Tüm Üniversiteler',
    'partners.search': 'Ortak ara...',
    'partners.allRegions': 'Tüm Bölgeler',
    'partners.refresh': 'Yenile',
    'partners.viewProfile': 'Profili Görüntüle',
    'partners.initiateMOU': 'MOU Başlat',
    'partners.matchScore': 'Eşleşme Puanı',
    
    // Mobility
    'mobility.title': 'Öğrenci Hareketlilik Yönetimi',
    'mobility.subtitle': 'Öğrenci hareketliliğini takip edin, başvuruları yönetin ve öğrenim anlaşmaları oluşturun',
    'mobility.selectUniversityPrompt': 'Lütfen üst menüden bir üniversite seçin.',
    'mobility.overview': 'Genel Bakış',
    'mobility.studentApplications': 'Öğrenci Başvuruları',
    'mobility.learningAgreements': 'Öğrenim Anlaşmaları',
    'mobility.dataFor': 'Hareketlilik verisi:',
    'mobility.incoming': 'Gelen',
    'mobility.outgoing': 'Giden',
    'mobility.incomingStudents': 'Gelen Öğrenciler',
    'mobility.outgoingStudents': 'Giden Öğrenciler',
    'mobility.partnerUniversities': 'Ortak Üniversiteler',
    'mobility.activePrograms': 'Aktif Programlar',
    'mobility.programDistribution': 'Program Dağılımı',
    'mobility.program.erasmus': 'Erasmus+',
    'mobility.program.bilateral': 'İkili Anlaşma',
    'mobility.program.exchange': 'Değişim',
    'mobility.program.jointDegree': 'Ortak Derece',
    'mobility.programType': 'Program Türü',
    'mobility.allPrograms': 'Tüm Programlar',
    'mobility.direction': 'Yön',
    'mobility.allDirections': 'Tüm Yönler',
    'mobility.academicYear': 'Akademik Yıl',
    'mobility.allYears': 'Tüm Yıllar',
    'mobility.filters': 'Filtreler:',
    'mobility.recordsTitle': 'Hareketlilik Kayıtları',
    'mobility.noRecords': 'Hareketlilik kaydı bulunamadı',
    'mobility.noRecordsDesc': 'Programlar aktif olduğunda hareketlilik verileri burada görünecek',
    'mobility.table.partnerUniversity': 'Ortak Üniversite',
    'mobility.table.program': 'Program',
    'mobility.table.direction': 'Yön',
    'mobility.table.students': 'Öğrenci',
    'mobility.table.academicYear': 'Akademik Yıl',
    'mobility.table.status': 'Durum',
    'mobility.ongoing': 'Devam Ediyor',
    'mobility.completed': 'Tamamlandı',
    'mobility.cancelled': 'İptal Edildi',
    'mobility.status': 'Durum',
    
    // MOU
    'mou.title': 'MOU Yönetimi',
    'mou.createNew': 'Yeni MOU Oluştur',
    'mou.status': 'Durum',
    'mou.partner': 'Ortak',
    'mou.clauses': 'Maddeler',
    'mou.history': 'Geçmiş',
    
    // Recruitment
    'recruitment.title': 'İşe Alım',
    'recruitment.subtitle': 'Uluslararası öğrenci işe alım takibi ve pazar analizi',
    'recruitment.selectUniversity': 'İşe alım verilerini görüntülemek için lütfen bir üniversite seçin.',
    'recruitment.editNumbers': 'Sayıları Düzenle',
    'recruitment.saved': 'Değişiklikler Kaydedildi',
    'recruitment.savedDesc': 'İşe alım verileri başarıyla güncellendi.',
    'recruitment.totalStudents': 'Toplam Öğrenci',
    'recruitment.countries': 'Ülkeler',
    'recruitment.acceptanceLetters': 'Kabul Mektupları',
    'recruitment.registered': 'Kayıtlı',
    'recruitment.frozen': 'Dondurulmuş',
    'recruitment.transfer': 'Transfer',
    'recruitment.deleted': 'Silinen',
    'recruitment.graduated': 'Mezun',
    'recruitment.byCountry': 'Ülkeye Göre',
    'recruitment.byAgency': 'Ajansa Göre',
    'recruitment.marketIntelligence': 'Pazar Analizi',
    'recruitment.studentsByCountry': 'Ülkeye Göre Öğrenciler',
    'recruitment.studentsByCountryDesc': 'Tüm işe alım metriklerinde ülkeye göre öğrenci sayılarını takip edin',
    'recruitment.studentsByAgency': 'Ajansa Göre Öğrenciler',
    'recruitment.studentsByAgencyDesc': 'Ortak ajanslar aracılığıyla öğrenci işe alımını takip edin',
    'recruitment.country': 'Ülke',
    'recruitment.agency': 'Ajans',
    'recruitment.students': 'Öğrenciler',
    'recruitment.mainCountries': 'Ana Ülkeler',
    'recruitment.commission': 'Komisyon',
    'recruitment.total': 'Toplam',
    'recruitment.avg': 'ort',
    'recruitment.agencies': 'ajans',
    'recruitment.analyzing': 'Analiz ediliyor...',
    'recruitment.analysisComplete': 'Analiz Tamamlandı',
    'recruitment.analysisCompleteDesc': 'Pazar analizi raporu başarıyla oluşturuldu.',
    'recruitment.analysisFailed': 'Analiz oluşturulamadı',
    'recruitment.analysisError': 'Analiz Hatası',
    'recruitment.generatingIntelligence': 'Pazar analizi oluşturuluyor...',
    'recruitment.totalApplications': 'Toplam Başvuru',
    'recruitment.avgConversion': 'Ort. Dönüşüm',
    'recruitment.marketsToScale': 'Büyütülecek Pazarlar',
    'recruitment.marketsToPause': 'Duraklatılacak Pazarlar',
    'recruitment.marketsToExit': 'Çıkılacak Pazarlar',
    
    // Market Intelligence
    'intelligence.title': 'Pazar Analizi',
    'intelligence.subtitle': 'Yapay zeka destekli pazar analizi ve stratejik öneriler',
    'intelligence.generateAnalysis': 'Analiz Oluştur',
    'intelligence.regenerate': 'Yeniden Oluştur',
    'intelligence.recommendations': 'Yapay Zeka Önerileri',
    'intelligence.metrics': 'Pazar Metrikleri',
    'intelligence.confidence': 'Güven',
    'intelligence.risk': 'Risk Seviyesi',
    'intelligence.keyMetrics': 'Anahtar Metrikler',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.add': 'Ekle',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.refresh': 'Yenile',
    'common.generate': 'Oluştur',
    'common.download': 'İndir',
    'common.upload': 'Yükle',
    'common.submit': 'Gönder',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.completed': 'Tamamlandı',
    'common.pending': 'Beklemede',
    'common.active': 'Aktif',
    'common.inactive': 'Pasif',
    'common.draft': 'Taslak',
    'common.approved': 'Onaylandı',
    'common.rejected': 'Reddedildi',
    'common.students': 'öğrenci',
    'common.records': 'kayıt',
    'common.unknown': 'Bilinmiyor',
  },
  de: {
    // Header
    'header.viewingAs': 'Anzeige als:',
    'header.selectUniversity': 'Universität auswählen',
    'header.loading': 'Laden...',
    'header.turkishUniversities': 'Türkische Universitäten',
    'header.internationalUniversities': 'Internationale Universitäten',
    'header.signOut': 'Abmelden',
    'header.language': 'Sprache',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profil',
    'nav.partners': 'Partner',
    'nav.mobility': 'Mobilität',
    'nav.mou': 'MOU',
    'nav.partnerships': 'Partnerschaften',
    'nav.intelligence': 'Marktanalyse',
    'nav.partnerAnalytics': 'Analytik',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.activePartnerships': 'Aktive Partnerschaften',
    'dashboard.pendingMOUs': 'Ausstehende MOUs',
    'dashboard.mobilityBalance': 'Mobilitätsbilanz',
    'dashboard.actionItems': 'Aktionspunkte',
    'dashboard.mobilityTrends': 'Mobilitätstrends',
    'dashboard.mouStatus': 'MOU-Status',
    'dashboard.partnersByRegion': 'Partner nach Region',
    'dashboard.projectsOverview': 'Projektübersicht',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.marketIntelligence': 'Marktanalyse',
    
    // Profile
    'profile.title': 'Universitätsprofil',
    'profile.subtitle': 'KI-gestützte institutionelle Analyse und strategische Intelligenz',
    'profile.healthIndex': 'Institutioneller Gesundheitsindex',
    'profile.overallScore': 'Gesamtpunktzahl',
    'profile.executiveSummary': 'Zusammenfassung',
    'profile.strengths': 'Stärken',
    'profile.weaknesses': 'Schwächen',
    'profile.recommendations': 'Strategische Empfehlungen',
    'profile.departmentROI': 'Abteilungs-ROI-Analyse',
    
    // Partners
    'partners.title': 'Partnersuche',
    'partners.subtitle': 'KI-gestützte Partnerempfehlungen und Universitätsdatenbank',
    'partners.aiRecommended': 'KI-Empfehlungen',
    'partners.allUniversities': 'Alle Universitäten',
    'partners.search': 'Partner suchen...',
    'partners.allRegions': 'Alle Regionen',
    'partners.refresh': 'Aktualisieren',
    'partners.viewProfile': 'Profil anzeigen',
    'partners.initiateMOU': 'MOU starten',
    'partners.matchScore': 'Übereinstimmung',
    
    // Mobility
    'mobility.title': 'Studentenmobilitätsverwaltung',
    'mobility.subtitle': 'Verfolgen Sie die Studentenmobilität, verwalten Sie Anträge und erstellen Sie Lernvereinbarungen',
    'mobility.selectUniversityPrompt': 'Bitte wählen Sie eine Universität im Header aus.',
    'mobility.overview': 'Übersicht',
    'mobility.studentApplications': 'Studentenanträge',
    'mobility.learningAgreements': 'Lernvereinbarungen',
    'mobility.dataFor': 'Mobilitätsdaten für',
    'mobility.incoming': 'Eingehend',
    'mobility.outgoing': 'Ausgehend',
    'mobility.incomingStudents': 'Eingehende Studierende',
    'mobility.outgoingStudents': 'Ausgehende Studierende',
    'mobility.partnerUniversities': 'Partneruniversitäten',
    'mobility.activePrograms': 'Aktive Programme',
    'mobility.programDistribution': 'Programmverteilung',
    'mobility.program.erasmus': 'Erasmus+',
    'mobility.program.bilateral': 'Bilateral',
    'mobility.program.exchange': 'Austausch',
    'mobility.program.jointDegree': 'Gemeinsamer Abschluss',
    'mobility.programType': 'Programmtyp',
    'mobility.allPrograms': 'Alle Programme',
    'mobility.direction': 'Richtung',
    'mobility.allDirections': 'Alle Richtungen',
    'mobility.academicYear': 'Akademisches Jahr',
    'mobility.allYears': 'Alle Jahre',
    'mobility.filters': 'Filter:',
    'mobility.recordsTitle': 'Mobilitätsdaten',
    'mobility.noRecords': 'Keine Mobilitätsdaten gefunden',
    'mobility.noRecordsDesc': 'Mobilitätsdaten erscheinen hier, sobald Programme aktiv sind',
    'mobility.table.partnerUniversity': 'Partneruniversität',
    'mobility.table.program': 'Programm',
    'mobility.table.direction': 'Richtung',
    'mobility.table.students': 'Studierende',
    'mobility.table.academicYear': 'Akademisches Jahr',
    'mobility.table.status': 'Status',
    'mobility.ongoing': 'Laufend',
    'mobility.completed': 'Abgeschlossen',
    'mobility.cancelled': 'Abgebrochen',
    'mobility.status': 'Status',
    
    // MOU
    'mou.title': 'MOU-Verwaltung',
    'mou.createNew': 'Neues MOU erstellen',
    'mou.status': 'Status',
    'mou.partner': 'Partner',
    'mou.clauses': 'Klauseln',
    'mou.history': 'Verlauf',
    
    // Recruitment
    'recruitment.title': 'Rekrutierung',
    'recruitment.subtitle': 'Internationale Studentenrekrutierung und Marktanalyse',
    'recruitment.selectUniversity': 'Bitte wählen Sie eine Universität aus, um Rekrutierungsdaten anzuzeigen.',
    'recruitment.editNumbers': 'Zahlen bearbeiten',
    'recruitment.saved': 'Änderungen gespeichert',
    'recruitment.savedDesc': 'Rekrutierungsdaten wurden erfolgreich aktualisiert.',
    'recruitment.totalStudents': 'Gesamtstudierende',
    'recruitment.countries': 'Länder',
    'recruitment.acceptanceLetters': 'Zulassungsbescheide',
    'recruitment.registered': 'Registriert',
    'recruitment.frozen': 'Eingefroren',
    'recruitment.transfer': 'Transfer',
    'recruitment.deleted': 'Gelöscht',
    'recruitment.graduated': 'Absolviert',
    'recruitment.byCountry': 'Nach Land',
    'recruitment.byAgency': 'Nach Agentur',
    'recruitment.marketIntelligence': 'Marktanalyse',
    'recruitment.studentsByCountry': 'Studierende nach Land',
    'recruitment.studentsByCountryDesc': 'Verfolgen Sie die Studentenzahlen nach Land für alle Rekrutierungsmetriken',
    'recruitment.studentsByAgency': 'Studierende nach Agentur',
    'recruitment.studentsByAgencyDesc': 'Verfolgen Sie die Studentenrekrutierung über Partneragenturen',
    'recruitment.country': 'Land',
    'recruitment.agency': 'Agentur',
    'recruitment.students': 'Studierende',
    'recruitment.mainCountries': 'Hauptländer',
    'recruitment.commission': 'Provision',
    'recruitment.total': 'Gesamt',
    'recruitment.avg': 'Durchschn.',
    'recruitment.agencies': 'Agenturen',
    'recruitment.analyzing': 'Analyse läuft...',
    'recruitment.analysisComplete': 'Analyse abgeschlossen',
    'recruitment.analysisCompleteDesc': 'Marktanalysebericht wurde erfolgreich erstellt.',
    'recruitment.analysisFailed': 'Analyse fehlgeschlagen',
    'recruitment.analysisError': 'Analysefehler',
    'recruitment.generatingIntelligence': 'Marktanalyse wird erstellt...',
    'recruitment.totalApplications': 'Gesamtbewerbungen',
    'recruitment.avgConversion': 'Durchschn. Konversion',
    'recruitment.marketsToScale': 'Zu skalierende Märkte',
    'recruitment.marketsToPause': 'Zu pausierende Märkte',
    'recruitment.marketsToExit': 'Zu verlassende Märkte',
    
    // Market Intelligence
    'intelligence.title': 'Marktanalyse',
    'intelligence.subtitle': 'KI-gestützte Marktanalyse und strategische Empfehlungen',
    'intelligence.generateAnalysis': 'Analyse erstellen',
    'intelligence.regenerate': 'Neu erstellen',
    'intelligence.recommendations': 'KI-Empfehlungen',
    'intelligence.metrics': 'Marktmetriken',
    'intelligence.confidence': 'Vertrauen',
    'intelligence.risk': 'Risikostufe',
    'intelligence.keyMetrics': 'Schlüsselmetriken',
    
    // Common
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.add': 'Hinzufügen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.refresh': 'Aktualisieren',
    'common.generate': 'Erstellen',
    'common.download': 'Herunterladen',
    'common.upload': 'Hochladen',
    'common.submit': 'Absenden',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.completed': 'Abgeschlossen',
    'common.pending': 'Ausstehend',
    'common.active': 'Aktiv',
    'common.inactive': 'Inaktiv',
    'common.draft': 'Entwurf',
    'common.approved': 'Genehmigt',
    'common.rejected': 'Abgelehnt',
    'common.students': 'Studierende',
    'common.records': 'Einträge',
    'common.unknown': 'Unbekannt',
  },
  ar: {
    // Header
    'header.viewingAs': 'العرض كـ:',
    'header.selectUniversity': 'اختر الجامعة',
    'header.loading': 'جاري التحميل...',
    'header.turkishUniversities': 'الجامعات التركية',
    'header.internationalUniversities': 'الجامعات الدولية',
    'header.signOut': 'تسجيل الخروج',
    'header.language': 'اللغة',
    
    // Navigation
    'nav.dashboard': 'لوحة التحكم',
    'nav.profile': 'الملف الشخصي',
    'nav.partners': 'الشركاء',
    'nav.mobility': 'التنقل',
    'nav.mou': 'مذكرة التفاهم',
    'nav.partnerships': 'الشراكات',
    'nav.intelligence': 'تحليل السوق',
    'nav.partnerAnalytics': 'التحليلات',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.activePartnerships': 'الشراكات النشطة',
    'dashboard.pendingMOUs': 'مذكرات التفاهم المعلقة',
    'dashboard.mobilityBalance': 'ميزان التنقل',
    'dashboard.actionItems': 'عناصر العمل',
    'dashboard.mobilityTrends': 'اتجاهات التنقل',
    'dashboard.mouStatus': 'حالة مذكرة التفاهم',
    'dashboard.partnersByRegion': 'الشركاء حسب المنطقة',
    'dashboard.projectsOverview': 'نظرة عامة على المشاريع',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.marketIntelligence': 'تحليل السوق',
    
    // Profile
    'profile.title': 'ملف الجامعة',
    'profile.subtitle': 'تحليل مؤسسي مدعوم بالذكاء الاصطناعي واستخبارات استراتيجية',
    'profile.healthIndex': 'مؤشر الصحة المؤسسية',
    'profile.overallScore': 'النتيجة الإجمالية',
    'profile.executiveSummary': 'الملخص التنفيذي',
    'profile.strengths': 'نقاط القوة',
    'profile.weaknesses': 'نقاط الضعف',
    'profile.recommendations': 'التوصيات الاستراتيجية',
    'profile.departmentROI': 'تحليل عائد الاستثمار للأقسام',
    
    // Partners
    'partners.title': 'اكتشاف الشركاء',
    'partners.subtitle': 'توصيات الشركاء المدعومة بالذكاء الاصطناعي وقاعدة بيانات الجامعات',
    'partners.aiRecommended': 'توصيات الذكاء الاصطناعي',
    'partners.allUniversities': 'جميع الجامعات',
    'partners.search': 'البحث عن شركاء...',
    'partners.allRegions': 'جميع المناطق',
    'partners.refresh': 'تحديث',
    'partners.viewProfile': 'عرض الملف',
    'partners.initiateMOU': 'بدء مذكرة التفاهم',
    'partners.matchScore': 'درجة التطابق',
    
    // Mobility
    'mobility.title': 'إدارة تنقل الطلاب',
    'mobility.subtitle': 'تتبع تنقل الطلاب، وإدارة الطلبات، وإنشاء اتفاقيات التعلم',
    'mobility.selectUniversityPrompt': 'يرجى اختيار جامعة من الشريط العلوي.',
    'mobility.overview': 'نظرة عامة',
    'mobility.studentApplications': 'طلبات الطلاب',
    'mobility.learningAgreements': 'اتفاقيات التعلم',
    'mobility.dataFor': 'بيانات التنقل لـ',
    'mobility.incoming': 'الوارد',
    'mobility.outgoing': 'الصادر',
    'mobility.incomingStudents': 'الطلاب الواردون',
    'mobility.outgoingStudents': 'الطلاب الصادرون',
    'mobility.partnerUniversities': 'الجامعات الشريكة',
    'mobility.activePrograms': 'البرامج النشطة',
    'mobility.programDistribution': 'توزيع البرامج',
    'mobility.program.erasmus': 'Erasmus+',
    'mobility.program.bilateral': 'ثنائي',
    'mobility.program.exchange': 'تبادل',
    'mobility.program.jointDegree': 'درجة مشتركة',
    'mobility.programType': 'نوع البرنامج',
    'mobility.allPrograms': 'جميع البرامج',
    'mobility.direction': 'الاتجاه',
    'mobility.allDirections': 'جميع الاتجاهات',
    'mobility.academicYear': 'السنة الأكاديمية',
    'mobility.allYears': 'جميع السنوات',
    'mobility.filters': 'التصفية:',
    'mobility.recordsTitle': 'سجلات التنقل',
    'mobility.noRecords': 'لم يتم العثور على سجلات تنقل',
    'mobility.noRecordsDesc': 'ستظهر بيانات التنقل هنا بمجرد تفعيل البرامج',
    'mobility.table.partnerUniversity': 'الجامعة الشريكة',
    'mobility.table.program': 'البرنامج',
    'mobility.table.direction': 'الاتجاه',
    'mobility.table.students': 'الطلاب',
    'mobility.table.academicYear': 'السنة الأكاديمية',
    'mobility.table.status': 'الحالة',
    'mobility.ongoing': 'قيد التنفيذ',
    'mobility.completed': 'مكتمل',
    'mobility.cancelled': 'ملغي',
    'mobility.status': 'الحالة',
    
    // MOU
    'mou.title': 'إدارة مذكرة التفاهم',
    'mou.createNew': 'إنشاء مذكرة تفاهم جديدة',
    'mou.status': 'الحالة',
    'mou.partner': 'الشريك',
    'mou.clauses': 'البنود',
    'mou.history': 'السجل',
    
    // Recruitment
    'recruitment.title': 'التوظيف',
    'recruitment.subtitle': 'تتبع توظيف الطلاب الدوليين وتحليل السوق',
    'recruitment.selectUniversity': 'الرجاء اختيار جامعة لعرض بيانات التوظيف.',
    'recruitment.editNumbers': 'تعديل الأرقام',
    'recruitment.saved': 'تم حفظ التغييرات',
    'recruitment.savedDesc': 'تم تحديث بيانات التوظيف بنجاح.',
    'recruitment.totalStudents': 'إجمالي الطلاب',
    'recruitment.countries': 'الدول',
    'recruitment.acceptanceLetters': 'رسائل القبول',
    'recruitment.registered': 'مسجل',
    'recruitment.frozen': 'مجمد',
    'recruitment.transfer': 'تحويل',
    'recruitment.deleted': 'محذوف',
    'recruitment.graduated': 'تخرجوا',
    'recruitment.byCountry': 'حسب الدولة',
    'recruitment.byAgency': 'حسب الوكالة',
    'recruitment.marketIntelligence': 'تحليل السوق',
    'recruitment.studentsByCountry': 'الطلاب حسب الدولة',
    'recruitment.studentsByCountryDesc': 'تتبع أعداد الطلاب عبر جميع مقاييس التوظيف حسب الدولة',
    'recruitment.studentsByAgency': 'الطلاب حسب الوكالة',
    'recruitment.studentsByAgencyDesc': 'تتبع توظيف الطلاب من خلال الوكالات الشريكة',
    'recruitment.country': 'الدولة',
    'recruitment.agency': 'الوكالة',
    'recruitment.students': 'الطلاب',
    'recruitment.mainCountries': 'الدول الرئيسية',
    'recruitment.commission': 'العمولة',
    'recruitment.total': 'المجموع',
    'recruitment.avg': 'متوسط',
    'recruitment.agencies': 'وكالات',
    'recruitment.analyzing': 'جاري التحليل...',
    'recruitment.analysisComplete': 'اكتمل التحليل',
    'recruitment.analysisCompleteDesc': 'تم إنشاء تقرير تحليل السوق بنجاح.',
    'recruitment.analysisFailed': 'فشل في إنشاء التحليل',
    'recruitment.analysisError': 'خطأ في التحليل',
    'recruitment.generatingIntelligence': 'جاري إنشاء تحليل السوق...',
    'recruitment.totalApplications': 'إجمالي الطلبات',
    'recruitment.avgConversion': 'متوسط التحويل',
    'recruitment.marketsToScale': 'أسواق للتوسع',
    'recruitment.marketsToPause': 'أسواق للإيقاف',
    'recruitment.marketsToExit': 'أسواق للخروج',
    
    // Market Intelligence
    'intelligence.title': 'تحليل السوق',
    'intelligence.subtitle': 'تحليل السوق والتوصيات الاستراتيجية المدعومة بالذكاء الاصطناعي',
    'intelligence.generateAnalysis': 'إنشاء التحليل',
    'intelligence.regenerate': 'إعادة الإنشاء',
    'intelligence.recommendations': 'توصيات الذكاء الاصطناعي',
    'intelligence.metrics': 'مقاييس السوق',
    'intelligence.confidence': 'الثقة',
    'intelligence.risk': 'مستوى المخاطر',
    'intelligence.keyMetrics': 'المقاييس الرئيسية',
    
    // Common
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.refresh': 'تحديث',
    'common.generate': 'إنشاء',
    'common.download': 'تحميل',
    'common.upload': 'رفع',
    'common.submit': 'إرسال',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.completed': 'مكتمل',
    'common.pending': 'معلق',
    'common.active': 'نشط',
    'common.inactive': 'غير نشط',
    'common.draft': 'مسودة',
    'common.approved': 'موافق عليه',
    'common.rejected': 'مرفوض',
    'common.students': 'طالب',
    'common.records': 'سجل',
    'common.unknown': 'غير معروف',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  tr: 'Türkçe',
  de: 'Deutsch',
  ar: 'العربية',
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('iris-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('iris-language', lang);
    // Update document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    // Set initial direction
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { languageNames };
