import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'tr' | 'de' | 'ar';

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations for all supported languages
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.viewingAs': 'Viewing as:',
    'header.selectUniversity': 'Select University',
    'header.loading': 'Loading...',
    'header.turkishUniversities': 'Turkish Universities',
    'header.internationalUniversities': 'International Universities',
    'header.signOut': 'Sign Out',
    'header.language': 'Language',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profile',
    'nav.partners': 'Partners',
    'nav.mobility': 'Mobility',
    'nav.mou': 'MOU',
    'nav.partnerships': 'Partnerships',
    'nav.intelligence': 'Intelligence',
    'nav.partnerAnalytics': 'Analytics',
    'nav.documentation': 'Documentation',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'AI-driven governance intelligence for',
    'dashboard.activePartnerships': 'Active Partnerships',
    'dashboard.pendingMOUs': 'Pending MOUs',
    'dashboard.mobilityBalance': 'Mobility Balance',
    'dashboard.actionItems': 'Action Items',
    'dashboard.mobilityTrends': 'Mobility Trends',
    'dashboard.mouStatus': 'MOU Status',
    'dashboard.partnersByRegion': 'Partners by Region',
    'dashboard.projectsOverview': 'Projects Overview',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.marketIntelligence': 'Market Intelligence',
    'dashboard.institution': 'institution',
    'dashboard.rank': 'Rank',
    'dashboard.internationalization': 'internationalization',
    'dashboard.viaSigned': 'via signed MOUs',
    'dashboard.drafts': 'drafts',
    'dashboard.awaitingResponse': 'awaiting response',
    'dashboard.in': 'in',
    'dashboard.out': 'out',
    'dashboard.requests': 'requests',
    'dashboard.messages': 'messages',
    'dashboard.studentExchangesByYear': 'Student exchanges by academic year',
    'dashboard.currentAgreementDist': 'Current agreement distribution',
    'dashboard.noMobilityData': 'No mobility data available',
    'dashboard.noMOUData': 'No MOU data available',
    'dashboard.noPartnerData': 'No partner data',
    'dashboard.totalProjects': 'Total Projects',
    'dashboard.viewAllProjects': 'View all projects',
    'dashboard.manageMOUs': 'Manage MOUs',
    'dashboard.discoverPartners': 'Discover Partners',
    'dashboard.trackMobility': 'Track Mobility',
    'dashboard.viewProfile': 'View Profile',
    'dashboard.activeAgreements': 'Active Agreements',
    'dashboard.pendingReview': 'Pending Review',
    'dashboard.totalExchanges': 'Total Exchanges',
    'dashboard.activeProjects': 'Active Projects',
    'dashboard.draft': 'Draft',
    'dashboard.pending': 'Pending',
    'dashboard.signed': 'Signed',
    'dashboard.incoming': 'Incoming',
    'dashboard.outgoing': 'Outgoing',
    'dashboard.yourInstitution': 'your institution',
    
    // Profile
    'profile.title': 'University Profile',
    'profile.subtitle': 'AI-generated institutional analysis and strategic intelligence',
    'profile.healthIndex': 'Institutional Health Index',
    'profile.overallScore': 'Overall Score',
    'profile.executiveSummary': 'Executive Summary',
    'profile.strengths': 'Strengths',
    'profile.weaknesses': 'Weaknesses',
    'profile.recommendations': 'Strategic Recommendations',
    'profile.departmentROI': 'Department ROI Analysis',
    'profile.loading': 'Loading...',
    'profile.selectUniversity': 'Please select a university from the header.',
    'profile.institution': 'institution',
    'profile.recruitmentEfficiency': 'Recruitment Efficiency',
    'profile.offerToEnrollment': 'Offer-to-Enrollment Quality',
    'profile.retentionStability': 'Retention Stability',
    'profile.internationalizationImpact': 'Internationalization Impact',
    'profile.mobilityParticipation': 'Mobility Participation',
    'profile.partnerPerformance': 'Partner Performance',
    'profile.strengthsAndWeaknesses': 'Strengths & Weaknesses',
    'profile.topStrengths': 'Top Strengths',
    'profile.areasForImprovement': 'Areas for Improvement',
    'profile.scale': 'Scale',
    'profile.maintain': 'Maintain',
    'profile.reformRequired': 'Reform Required',
    'profile.partnerNeeded': 'Partner Needed',
    'profile.adjustCapacity': 'Adjust Capacity',
    'profile.department': 'Department',
    'profile.roiScore': 'ROI Score',
    'profile.studentVolume': 'Student Volume',
    'profile.action': 'Action',
    'profile.noDataAvailable': 'No data available',
    'profile.generateAnalysis': 'Generate Analysis',
    'profile.aiGenerating': 'AI is generating analysis...',
    
    // Partners
    'partners.title': 'Partner Discovery',
    'partners.subtitle': 'AI-powered partner recommendations based on strategic alignment and complementarity',
    'partners.aiRecommended': 'AI Recommended',
    'partners.allUniversities': 'All Universities',
    'partners.search': 'Search universities...',
    'partners.allRegions': 'All Regions',
    'partners.refresh': 'Refresh',
    'partners.viewProfile': 'View Profile',
    'partners.initiateMOU': 'Initiate MOU',
    'partners.matchScore': 'Match Score',
    'partners.findingPartnersFor': 'Finding partners for',
    'partners.aiRecommendedPartners': 'AI-recommended partners',
    'partners.noRecommendations': 'No recommendations generated yet',
    'partners.generateRecommendations': 'Generate Recommendations',
    'partners.universitiesAvailable': 'universities available',
    'partners.analyzingPartnerships': 'Analyzing strategic partnerships...',
    'partners.strategicFit': 'Strategic Fit',
    'partners.keyStrengths': 'Key Strengths',
    'partners.complementaryAreas': 'Complementary Areas',
    'partners.showMore': 'Show More',
    'partners.showLess': 'Show Less',
    
    // Mobility
    'mobility.title': 'Student Mobility Management',
    'mobility.subtitle': 'Track student mobility, manage applications, and generate learning agreements',
    'mobility.selectUniversityPrompt': 'Please select a university from the header.',
    'mobility.overview': 'Overview',
    'mobility.studentApplications': 'Student Applications',
    'mobility.learningAgreements': 'Learning Agreements',
    'mobility.dataFor': 'Mobility data for',
    'mobility.incoming': 'Incoming',
    'mobility.outgoing': 'Outgoing',
    'mobility.incomingStudents': 'Incoming Students',
    'mobility.outgoingStudents': 'Outgoing Students',
    'mobility.partnerUniversities': 'Partner Universities',
    'mobility.activePrograms': 'Active Programs',
    'mobility.programDistribution': 'Program Distribution',
    'mobility.program.erasmus': 'Erasmus+',
    'mobility.program.bilateral': 'Bilateral',
    'mobility.program.exchange': 'Exchange',
    'mobility.program.jointDegree': 'Joint Degree',
    'mobility.programType': 'Program Type',
    'mobility.allPrograms': 'All Programs',
    'mobility.direction': 'Direction',
    'mobility.allDirections': 'All Directions',
    'mobility.academicYear': 'Academic Year',
    'mobility.allYears': 'All Years',
    'mobility.filters': 'Filters:',
    'mobility.recordsTitle': 'Mobility Records',
    'mobility.noRecords': 'No mobility records found',
    'mobility.noRecordsDesc': 'Mobility data will appear here once programs are active',
    'mobility.table.partnerUniversity': 'Partner University',
    'mobility.table.program': 'Program',
    'mobility.table.direction': 'Direction',
    'mobility.table.students': 'Students',
    'mobility.table.academicYear': 'Academic Year',
    'mobility.table.status': 'Status',
    'mobility.ongoing': 'Ongoing',
    'mobility.completed': 'Completed',
    'mobility.cancelled': 'Cancelled',
    'mobility.status': 'Status',
    
    // MOU
    'mou.title': 'MOU Management',
    'mou.createNew': 'Create New MOU',
    'mou.status': 'Status',
    'mou.partner': 'Partner',
    'mou.clauses': 'Clauses',
    'mou.history': 'History',
    'mou.subtitle': 'Draft, negotiate, and finalize memorandums of understanding',
    'mou.selectPartner': 'Select a Partner University',
    'mou.selectPartnerDesc': 'Choose a partner university to create or manage an MOU',
    'mou.selectPartnerPlaceholder': 'Select a partner university...',
    'mou.browsePartnersText': 'Or browse partners on the',
    'mou.partnerDiscovery': 'Partner Discovery',
    'mou.pageToFindMatch': 'page to find the right match.',
    'mou.cooperationScope': 'Cooperation Scope',
    'mou.aiClauseRecommendations': 'AI Clause Recommendations',
    'mou.generateSuggestions': 'Generate Suggestions',
    'mou.selectScopeFirst': 'Select cooperation scope areas above to generate AI recommendations',
    'mou.initiator': 'Initiator',
    'mou.save': 'Save MOU',
    'mou.existingMOUs': 'Existing MOUs',
    'mou.noExistingMOUs': 'No existing MOUs found',
    'mou.clauseTitle': 'Agreement Clauses',
    'mou.addClause': 'Add Clause',
    'mou.saved': 'Saved',
    'mou.savedDesc': 'MOU updated successfully',
    'mou.created': 'Created',
    'mou.createdDesc': 'MOU created successfully',
    'mou.error': 'Error',
    'mou.errorDesc': 'Failed to save MOU',
    'mou.statusUpdated': 'Status Updated',
    'mou.scope.studentExchange': 'Student Exchange',
    'mou.scope.facultyExchange': 'Faculty Exchange',
    'mou.scope.jointResearch': 'Joint Research',
    'mou.scope.jointDegree': 'Joint Degree Programs',
    'mou.scope.summerSchool': 'Summer Schools',
    'mou.scope.conferences': 'Joint Conferences',
    'mou.scope.publications': 'Joint Publications',
    'mou.scope.resourceSharing': 'Resource Sharing',
    
    // Partnership Management
    'partnerships.title': 'Partnership Management',
    'partnerships.subtitle': 'AI-powered partner management, project tracking, and request handling',
    'partnerships.activePartners': 'Active Partners',
    'partnerships.activeProjects': 'Active Projects',
    'partnerships.pendingRequests': 'Pending Requests',
    'partnerships.unreadMessages': 'Unread Messages',
    'partnerships.aiAdvisor': 'AI Advisor',
    'partnerships.projects': 'Projects',
    'partnerships.requests': 'Requests',
    'partnerships.messagesTab': 'Messages',
    'partnerships.aiPartnershipAdvisor': 'AI Partnership Advisor',
    'partnerships.generateRecommendations': 'Generate Recommendations',
    'partnerships.overallStrategy': 'Overall Strategy',
    'partnerships.nextSteps': 'Next Steps',
    'partnerships.opportunity': 'Opportunity',
    'partnerships.risk': 'Risk',
    'partnerships.priority': 'priority',
    'partnerships.initiateMOU': 'Initiate MOU',
    'partnerships.message': 'Message',
    'partnerships.noPartners': 'No active partnerships yet',
    'partnerships.noPartnersDesc': 'Discover and initiate partnerships on the Partner Discovery page',
    'partnerships.sendMessage': 'Send Message',
    'partnerships.subject': 'Subject',
    'partnerships.messageContent': 'Message',
    'partnerships.send': 'Send',
    'partnerships.sent': 'Sent',
    'partnerships.sentDesc': 'Message sent successfully',
    'partnerships.accept': 'Accept',
    'partnerships.reject': 'Reject',
    'partnerships.accepted': 'Accepted',
    'partnerships.rejected': 'Rejected',
    'partnerships.requestUpdated': 'Request has been',
    'partnerships.noProjects': 'No projects found',
    'partnerships.noRequests': 'No pending requests',
    'partnerships.noMessages': 'No messages',
    'partnerships.from': 'From',
    'partnerships.to': 'To',
    'partnerships.date': 'Date',
    'partnerships.progress': 'Progress',
    'partnerships.budget': 'Budget',
    'partnerships.startDate': 'Start',
    'partnerships.endDate': 'End',
    
    // Partner Analytics
    'analytics.title': 'Partner Analytics',
    'analytics.subtitle': 'Comprehensive analytics across all partnership agreements for',
    'analytics.partners': 'Partners',
    'analytics.countries': 'Countries',
    'analytics.exchanges': 'Exchanges',
    'analytics.funding': 'Funding',
    'analytics.publications': 'Publications',
    'analytics.avgSatisfaction': 'Avg Satisfaction',
    'analytics.studentMobilityTrend': 'Student Mobility Trend',
    'analytics.incomingVsOutgoing': 'Incoming vs Outgoing by academic year',
    'analytics.agreementTypeDist': 'Agreement Type Distribution',
    'analytics.partnersByProgram': 'Partners by program type',
    'analytics.partnerDistByCountry': 'Partner Distribution by Country',
    'analytics.studentsExchanged': 'students exchanged',
    'analytics.partnersLabel': 'partners',
    'analytics.partnerPerformance': 'Partner Performance Overview',
    'analytics.detailedMetrics': 'Detailed metrics for each partner university',
    'analytics.sortBy': 'Sort by',
    'analytics.filterByRegion': 'Filter by Region',
    'analytics.allRegions': 'All Regions',
    'analytics.totalStudents': 'Total Students',
    'analytics.satisfaction': 'Satisfaction',
    'analytics.name': 'Name',
    'analytics.university': 'University',
    'analytics.country': 'Country',
    'analytics.inOut': 'In/Out',
    'analytics.research': 'Research',
    'analytics.noMobilityData': 'No mobility data',
    'analytics.noProgramData': 'No program data',
    
    // Recruitment
    'recruitment.title': 'Recruitment',
    'recruitment.subtitle': 'International student recruitment tracking and market intelligence',
    'recruitment.selectUniversity': 'Please select a university to view recruitment data.',
    'recruitment.editNumbers': 'Edit Numbers',
    'recruitment.saved': 'Changes Saved',
    'recruitment.savedDesc': 'Recruitment data has been updated successfully.',
    'recruitment.totalStudents': 'Total Students',
    'recruitment.countries': 'Countries',
    'recruitment.acceptanceLetters': 'Acceptance Letters',
    'recruitment.registered': 'Registered',
    'recruitment.frozen': 'Frozen',
    'recruitment.transfer': 'Transfer',
    'recruitment.deleted': 'Deleted',
    'recruitment.graduated': 'Graduated',
    'recruitment.byCountry': 'By Country',
    'recruitment.byAgency': 'By Agency',
    'recruitment.marketIntelligence': 'Market Intelligence',
    'recruitment.studentsByCountry': 'Students by Country',
    'recruitment.studentsByCountryDesc': 'Track student numbers across all recruitment metrics by country',
    'recruitment.studentsByAgency': 'Students by Agency',
    'recruitment.studentsByAgencyDesc': 'Track student recruitment through partner agencies',
    'recruitment.country': 'Country',
    'recruitment.agency': 'Agency',
    'recruitment.students': 'Students',
    'recruitment.mainCountries': 'Main Countries',
    'recruitment.commission': 'Commission',
    'recruitment.total': 'Total',
    'recruitment.avg': 'avg',
    'recruitment.agencies': 'agencies',
    'recruitment.analyzing': 'Analyzing...',
    'recruitment.analysisComplete': 'Analysis Complete',
    'recruitment.analysisCompleteDesc': 'Market intelligence report generated successfully.',
    'recruitment.analysisFailed': 'Failed to generate analysis',
    'recruitment.analysisError': 'Analysis Error',
    'recruitment.generatingIntelligence': 'Generating market intelligence...',
    'recruitment.totalApplications': 'Total Applications',
    'recruitment.avgConversion': 'Avg. Conversion',
    'recruitment.marketsToScale': 'Markets to Scale',
    'recruitment.marketsToPause': 'Markets to Pause',
    'recruitment.marketsToExit': 'Markets to Exit',
    'recruitment.fairs': 'Fairs',
    'recruitment.studentPlacement': 'Student Placement',
    'recruitment.nationalityDistribution': 'Nationality Distribution',
    'recruitment.overview': 'Overview',
    'recruitment.year': 'Year',
    
    // Market Intelligence
    'intelligence.title': 'Market Intelligence',
    'intelligence.subtitle': 'AI-powered market analysis and strategic recommendations',
    'intelligence.generateAnalysis': 'Generate Analysis',
    'intelligence.regenerate': 'Regenerate',
    'intelligence.recommendations': 'AI Recommendations',
    'intelligence.metrics': 'Market Metrics',
    'intelligence.confidence': 'Confidence',
    'intelligence.risk': 'Risk Level',
    'intelligence.keyMetrics': 'Key Metrics',
    'intelligence.refreshAnalysis': 'Refresh Analysis',
    'intelligence.analysisComplete': 'Analysis Complete',
    'intelligence.analysisCompleteDesc': 'Market intelligence report generated successfully.',
    'intelligence.analysisFailed': 'Failed to generate analysis',
    'intelligence.analysisError': 'Analysis Error',
    'intelligence.selectUniversity': 'Please select a university to view market intelligence.',
    'intelligence.recruitmentMarketAnalysis': 'AI-powered recruitment market analysis for',
    'intelligence.totalApplications': 'Total Applications',
    'intelligence.avgConversion': 'Avg. Conversion',
    'intelligence.marketsToScale': 'Markets to Scale',
    'intelligence.marketsToPause': 'Markets to Pause',
    'intelligence.marketsToExit': 'Markets to Exit',
    'intelligence.marketPerformance': 'Market Performance Metrics',
    'intelligence.detailedBreakdown': 'Detailed breakdown of recruitment metrics by country',
    'intelligence.applications': 'Applications',
    'intelligence.offers': 'Offers',
    'intelligence.enrollments': 'Enrollments',
    'intelligence.conversionPct': 'Conversion %',
    'intelligence.overOffering': 'Over-Offering',
    'intelligence.wasteRatio': 'Waste Ratio',
    'intelligence.agentPct': 'Agent %',
    'intelligence.channelQuality': 'Recruitment Channel Quality',
    'intelligence.highRiskMarkets': 'High-Risk Markets',
    'intelligence.noHighRisk': 'No high-risk markets identified',
    'intelligence.generatingReport': 'Generating comprehensive market intelligence report...',
    'intelligence.conversionEfficiency': 'Conversion Efficiency',
    'intelligence.recruitmentQuality': 'Recruitment Quality',
    'intelligence.capacityAlignment': 'Capacity Alignment',
    
    // Documentation
    'docs.title': 'Student Documentation Management',
    'docs.subtitle': 'Complete document requirements, country-specific rules, and student tracking',
    'docs.requirementsChecker': 'Requirements Checker',
    'docs.countryRules': 'Country Rules',
    'docs.studentTracking': 'Student Tracking',
    'docs.specialCases': 'Special Cases',
    'docs.selectUniversity': 'Please select a university to view documentation management.',
    'docs.selectStudentProfile': 'Select Student Profile',
    'docs.selectStudentDesc': 'Choose the student\'s situation to see required documents',
    'docs.studentStage': 'Student Stage',
    'docs.degreeLevel': 'Degree Level',
    'docs.countryOfOrigin': 'Country of Origin',
    'docs.educationSystem': 'Education System',
    'docs.selectStage': 'Select stage...',
    'docs.selectDegree': 'Select degree...',
    'docs.selectCountry': 'Select country...',
    'docs.selectEducation': 'Select education system...',
    'docs.getAIReqs': 'Get AI Requirements',
    'docs.requiredDocuments': 'Required Documents',
    'docs.template': 'Template',
    'docs.required': 'Required',
    'docs.optional': 'Optional',
    'docs.stamps': 'Stamps Required',
    'docs.howToObtain': 'How to Obtain',
    'docs.timeline': 'Timeline',
    'docs.notes': 'Notes',
    'docs.commonIssues': 'Common Issues',
    'docs.generalAdvice': 'General Advice',
    'docs.estimatedTime': 'Estimated Total Time',
    'docs.countrySpecificRules': 'Country-Specific Document Rules',
    'docs.countryRulesDesc': 'Document requirements and verification rules by country',
    'docs.searchCountries': 'Search countries...',
    'docs.noRulesFound': 'No country rules found',
    'docs.specificRequirements': 'Specific Requirements',
    'docs.studentDocTracking': 'Student Document Tracking',
    'docs.trackingDesc': 'Track and verify documents for individual students',
    'docs.addNewStudent': 'Add New Student',
    'docs.searchStudents': 'Search students...',
    'docs.allStatuses': 'All Statuses',
    'docs.inProgress': 'In Progress',
    'docs.complete': 'Complete',
    'docs.issues': 'Issues',
    'docs.studentName': 'Student Name',
    'docs.studentEmail': 'Student Email',
    'docs.studentId': 'Student ID',
    'docs.createTracking': 'Create Tracking',
    'docs.noStudentsFound': 'No students found',
    'docs.documentsVerified': 'documents verified',
    'docs.stage.newAdmission': 'New Admission',
    'docs.stage.enrolled': 'Enrolled Student',
    'docs.stage.freeze': 'Freeze Registration',
    'docs.stage.unfreeze': 'Unfreeze Registration',
    'docs.stage.transferIn': 'Transfer In (From Another University)',
    'docs.stage.transferOut': 'Transfer Out (To Another University)',
    'docs.degree.bachelors': "Bachelor's Degree",
    'docs.degree.masters': "Master's Degree",
    'docs.degree.phd': 'PhD / Doctorate',
    'docs.edu.national': 'National Curriculum',
    'docs.edu.cambridge': 'Cambridge (O-Levels/A-Levels)',
    'docs.edu.ib': 'International Baccalaureate (IB)',
    'docs.edu.american': 'American High School',
    'docs.edu.ged': 'GED',
    'docs.edu.cbse': 'CBSE (India)',
    'docs.edu.isc': 'ISC (India)',
    'docs.edu.waec': 'WAEC (West Africa)',
    'docs.edu.neco': 'NECO (Nigeria)',
    'docs.edu.other': 'Other',
    
    // Special Cases
    'specialCases.title': 'Special Cases Tracking',
    'specialCases.subtitle': 'Track and manage complex student enrollment cases',
    'specialCases.searchPlaceholder': 'Search by name, ID, or department...',
    'specialCases.allCategories': 'All Categories',
    'specialCases.allStatuses': 'All Statuses',
    'specialCases.credentialRecognition': 'Credential Recognition',
    'specialCases.academicFailure': 'Academic Failure',
    'specialCases.warZone': 'War Zone / Conflict',
    'specialCases.visaIssue': 'Visa Issue',
    'specialCases.other': 'Other',
    'specialCases.open': 'Open',
    'specialCases.inProgress': 'In Progress',
    'specialCases.pendingDocuments': 'Pending Documents',
    'specialCases.resolved': 'Resolved',
    'specialCases.escalated': 'Escalated',
    'specialCases.activeCases': 'active cases',
    'specialCases.caseDetails': 'Case Details',
    'specialCases.progressTimeline': 'Progress Timeline',
    'specialCases.noCasesFound': 'No cases found matching your criteria',
    'specialCases.department': 'Department',
    'specialCases.enrollmentYear': 'Enrollment Year',
    'specialCases.nationality': 'Nationality',
    'specialCases.issue': 'Issue',
    'specialCases.requiredAction': 'Required Action',
    
    // Auth
    'auth.title': 'IRIS',
    'auth.subtitle': 'International Relations Intelligent System',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.loginButton': 'Sign In',
    'auth.signupButton': 'Create Account',
    'auth.loggingIn': 'Signing in...',
    'auth.signingUp': 'Creating account...',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInToContinue': 'Sign in to continue to IRIS',
    'auth.createAccount': 'Create your account',
    'auth.getStarted': 'Get started with IRIS',
    'auth.checkEmail': 'Check your email',
    'auth.verifyEmail': 'Please verify your email address to continue.',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'common.generate': 'Generate',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.submit': 'Submit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.draft': 'Draft',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.students': 'students',
    'common.records': 'records',
    'common.unknown': 'Unknown',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.noData': 'No data available',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.region': 'Region',
    'common.date': 'Date',
  },
  tr: {
    // Header
    'header.viewingAs': 'Görüntülenen:',
    'header.selectUniversity': 'Üniversite Seçin',
    'header.loading': 'Yükleniyor...',
    'header.turkishUniversities': 'Türk Üniversiteleri',
    'header.internationalUniversities': 'Uluslararası Üniversiteler',
    'header.signOut': 'Çıkış Yap',
    'header.language': 'Dil',
    
    // Navigation
    'nav.dashboard': 'Gösterge Paneli',
    'nav.profile': 'Profil',
    'nav.partners': 'Ortaklar',
    'nav.mobility': 'Hareketlilik',
    'nav.mou': 'Protokol',
    'nav.partnerships': 'Ortaklıklar',
    'nav.intelligence': 'Pazar Analizi',
    'nav.partnerAnalytics': 'Analitik',
    'nav.documentation': 'Belge Yönetimi',
    
    // Dashboard
    'dashboard.title': 'Gösterge Paneli',
    'dashboard.subtitle': 'Yapay zeka destekli yönetişim istihbaratı:',
    'dashboard.activePartnerships': 'Aktif Ortaklıklar',
    'dashboard.pendingMOUs': 'Bekleyen Protokoller',
    'dashboard.mobilityBalance': 'Hareketlilik Dengesi',
    'dashboard.actionItems': 'Eylem Öğeleri',
    'dashboard.mobilityTrends': 'Hareketlilik Trendleri',
    'dashboard.mouStatus': 'Protokol Durumu',
    'dashboard.partnersByRegion': 'Bölgeye Göre Ortaklar',
    'dashboard.projectsOverview': 'Projeler Genel Bakış',
    'dashboard.quickActions': 'Hızlı İşlemler',
    'dashboard.marketIntelligence': 'Pazar Analizi',
    'dashboard.institution': 'kurum',
    'dashboard.rank': 'Sıralama',
    'dashboard.internationalization': 'uluslararasılaşma',
    'dashboard.viaSigned': 'imzalı protokollerle',
    'dashboard.drafts': 'taslak',
    'dashboard.awaitingResponse': 'yanıt bekliyor',
    'dashboard.in': 'gelen',
    'dashboard.out': 'giden',
    'dashboard.requests': 'talep',
    'dashboard.messages': 'mesaj',
    'dashboard.studentExchangesByYear': 'Akademik yıla göre öğrenci değişimleri',
    'dashboard.currentAgreementDist': 'Mevcut anlaşma dağılımı',
    'dashboard.noMobilityData': 'Hareketlilik verisi bulunamadı',
    'dashboard.noMOUData': 'Protokol verisi bulunamadı',
    'dashboard.noPartnerData': 'Ortak verisi yok',
    'dashboard.totalProjects': 'Toplam Proje',
    'dashboard.viewAllProjects': 'Tüm projeleri görüntüle',
    'dashboard.manageMOUs': 'Protokolleri Yönet',
    'dashboard.discoverPartners': 'Ortak Keşfet',
    'dashboard.trackMobility': 'Hareketliliği İzle',
    'dashboard.viewProfile': 'Profili Görüntüle',
    'dashboard.activeAgreements': 'Aktif Anlaşmalar',
    'dashboard.pendingReview': 'İnceleme Bekleyen',
    'dashboard.totalExchanges': 'Toplam Değişim',
    'dashboard.activeProjects': 'Aktif Projeler',
    'dashboard.draft': 'Taslak',
    'dashboard.pending': 'Beklemede',
    'dashboard.signed': 'İmzalı',
    'dashboard.incoming': 'Gelen',
    'dashboard.outgoing': 'Giden',
    'dashboard.yourInstitution': 'kurumunuz',
    
    // Profile
    'profile.title': 'Üniversite Profili',
    'profile.subtitle': 'Yapay zeka destekli kurumsal analiz ve stratejik istihbarat',
    'profile.healthIndex': 'Kurumsal Sağlık Endeksi',
    'profile.overallScore': 'Genel Puan',
    'profile.executiveSummary': 'Yönetici Özeti',
    'profile.strengths': 'Güçlü Yönler',
    'profile.weaknesses': 'Zayıf Yönler',
    'profile.recommendations': 'Stratejik Öneriler',
    'profile.departmentROI': 'Bölüm ROI Analizi',
    'profile.loading': 'Yükleniyor...',
    'profile.selectUniversity': 'Lütfen üst menüden bir üniversite seçin.',
    'profile.institution': 'kurum',
    'profile.recruitmentEfficiency': 'İşe Alım Verimliliği',
    'profile.offerToEnrollment': 'Teklif-Kayıt Kalitesi',
    'profile.retentionStability': 'Devam Oranı İstikrarı',
    'profile.internationalizationImpact': 'Uluslararasılaşma Etkisi',
    'profile.mobilityParticipation': 'Hareketlilik Katılımı',
    'profile.partnerPerformance': 'Ortak Performansı',
    'profile.strengthsAndWeaknesses': 'Güçlü ve Zayıf Yönler',
    'profile.topStrengths': 'Öne Çıkan Güçlü Yönler',
    'profile.areasForImprovement': 'Gelişim Alanları',
    'profile.scale': 'Ölçeklendir',
    'profile.maintain': 'Sürdür',
    'profile.reformRequired': 'Reform Gerekli',
    'profile.partnerNeeded': 'Ortak Gerekli',
    'profile.adjustCapacity': 'Kapasite Ayarla',
    'profile.department': 'Bölüm',
    'profile.roiScore': 'ROI Puanı',
    'profile.studentVolume': 'Öğrenci Hacmi',
    'profile.action': 'Eylem',
    'profile.noDataAvailable': 'Veri mevcut değil',
    'profile.generateAnalysis': 'Analiz Oluştur',
    'profile.aiGenerating': 'Yapay zeka analiz oluşturuyor...',
    
    // Partners
    'partners.title': 'Ortak Keşfi',
    'partners.subtitle': 'Stratejik uyum ve tamamlayıcılığa dayalı yapay zeka destekli ortak önerileri',
    'partners.aiRecommended': 'Yapay Zeka Önerileri',
    'partners.allUniversities': 'Tüm Üniversiteler',
    'partners.search': 'Üniversite ara...',
    'partners.allRegions': 'Tüm Bölgeler',
    'partners.refresh': 'Yenile',
    'partners.viewProfile': 'Profili Görüntüle',
    'partners.initiateMOU': 'Protokol Başlat',
    'partners.matchScore': 'Eşleşme Puanı',
    'partners.findingPartnersFor': 'Ortak aranıyor:',
    'partners.aiRecommendedPartners': 'Yapay zeka önerili ortak',
    'partners.noRecommendations': 'Henüz öneri oluşturulmadı',
    'partners.generateRecommendations': 'Önerileri Oluştur',
    'partners.universitiesAvailable': 'üniversite mevcut',
    'partners.analyzingPartnerships': 'Stratejik ortaklıklar analiz ediliyor...',
    'partners.strategicFit': 'Stratejik Uyum',
    'partners.keyStrengths': 'Temel Güçlü Yönler',
    'partners.complementaryAreas': 'Tamamlayıcı Alanlar',
    'partners.showMore': 'Daha Fazla Göster',
    'partners.showLess': 'Daha Az Göster',
    
    // Mobility
    'mobility.title': 'Öğrenci Hareketlilik Yönetimi',
    'mobility.subtitle': 'Öğrenci hareketliliğini takip edin, başvuruları yönetin ve öğrenim anlaşmaları oluşturun',
    'mobility.selectUniversityPrompt': 'Lütfen üst menüden bir üniversite seçin.',
    'mobility.overview': 'Genel Bakış',
    'mobility.studentApplications': 'Öğrenci Başvuruları',
    'mobility.learningAgreements': 'Öğrenim Anlaşmaları',
    'mobility.dataFor': 'Hareketlilik verisi:',
    'mobility.incoming': 'Gelen',
    'mobility.outgoing': 'Giden',
    'mobility.incomingStudents': 'Gelen Öğrenciler',
    'mobility.outgoingStudents': 'Giden Öğrenciler',
    'mobility.partnerUniversities': 'Ortak Üniversiteler',
    'mobility.activePrograms': 'Aktif Programlar',
    'mobility.programDistribution': 'Program Dağılımı',
    'mobility.program.erasmus': 'Erasmus+',
    'mobility.program.bilateral': 'İkili Anlaşma',
    'mobility.program.exchange': 'Değişim',
    'mobility.program.jointDegree': 'Ortak Derece',
    'mobility.programType': 'Program Türü',
    'mobility.allPrograms': 'Tüm Programlar',
    'mobility.direction': 'Yön',
    'mobility.allDirections': 'Tüm Yönler',
    'mobility.academicYear': 'Akademik Yıl',
    'mobility.allYears': 'Tüm Yıllar',
    'mobility.filters': 'Filtreler:',
    'mobility.recordsTitle': 'Hareketlilik Kayıtları',
    'mobility.noRecords': 'Hareketlilik kaydı bulunamadı',
    'mobility.noRecordsDesc': 'Programlar aktif olduğunda hareketlilik verileri burada görünecek',
    'mobility.table.partnerUniversity': 'Ortak Üniversite',
    'mobility.table.program': 'Program',
    'mobility.table.direction': 'Yön',
    'mobility.table.students': 'Öğrenci',
    'mobility.table.academicYear': 'Akademik Yıl',
    'mobility.table.status': 'Durum',
    'mobility.ongoing': 'Devam Ediyor',
    'mobility.completed': 'Tamamlandı',
    'mobility.cancelled': 'İptal Edildi',
    'mobility.status': 'Durum',
    
    // MOU
    'mou.title': 'Protokol Yönetimi',
    'mou.createNew': 'Yeni Protokol Oluştur',
    'mou.status': 'Durum',
    'mou.partner': 'Ortak',
    'mou.clauses': 'Maddeler',
    'mou.history': 'Geçmiş',
    'mou.subtitle': 'Mutabakat zaptlarını hazırlayın, müzakere edin ve sonuçlandırın',
    'mou.selectPartner': 'Ortak Üniversite Seçin',
    'mou.selectPartnerDesc': 'Protokol oluşturmak veya yönetmek için bir ortak üniversite seçin',
    'mou.selectPartnerPlaceholder': 'Bir ortak üniversite seçin...',
    'mou.browsePartnersText': 'Veya ortakları şurada arayın:',
    'mou.partnerDiscovery': 'Ortak Keşfi',
    'mou.pageToFindMatch': 'doğru eşleşmeyi bulmak için.',
    'mou.cooperationScope': 'İşbirliği Kapsamı',
    'mou.aiClauseRecommendations': 'Yapay Zeka Madde Önerileri',
    'mou.generateSuggestions': 'Önerileri Oluştur',
    'mou.selectScopeFirst': 'Yapay zeka önerileri almak için yukarıdan işbirliği kapsamı seçin',
    'mou.initiator': 'Başlatan',
    'mou.save': 'Protokolü Kaydet',
    'mou.existingMOUs': 'Mevcut Protokoller',
    'mou.noExistingMOUs': 'Mevcut protokol bulunamadı',
    'mou.clauseTitle': 'Anlaşma Maddeleri',
    'mou.addClause': 'Madde Ekle',
    'mou.saved': 'Kaydedildi',
    'mou.savedDesc': 'Protokol başarıyla güncellendi',
    'mou.created': 'Oluşturuldu',
    'mou.createdDesc': 'Protokol başarıyla oluşturuldu',
    'mou.error': 'Hata',
    'mou.errorDesc': 'Protokol kaydedilemedi',
    'mou.statusUpdated': 'Durum Güncellendi',
    'mou.scope.studentExchange': 'Öğrenci Değişimi',
    'mou.scope.facultyExchange': 'Akademisyen Değişimi',
    'mou.scope.jointResearch': 'Ortak Araştırma',
    'mou.scope.jointDegree': 'Ortak Diploma Programları',
    'mou.scope.summerSchool': 'Yaz Okulları',
    'mou.scope.conferences': 'Ortak Konferanslar',
    'mou.scope.publications': 'Ortak Yayınlar',
    'mou.scope.resourceSharing': 'Kaynak Paylaşımı',
    
    // Partnership Management
    'partnerships.title': 'Ortaklık Yönetimi',
    'partnerships.subtitle': 'Yapay zeka destekli ortak yönetimi, proje takibi ve talep yönetimi',
    'partnerships.activePartners': 'Aktif Ortaklar',
    'partnerships.activeProjects': 'Aktif Projeler',
    'partnerships.pendingRequests': 'Bekleyen Talepler',
    'partnerships.unreadMessages': 'Okunmamış Mesajlar',
    'partnerships.aiAdvisor': 'YZ Danışmanı',
    'partnerships.projects': 'Projeler',
    'partnerships.requests': 'Talepler',
    'partnerships.messagesTab': 'Mesajlar',
    'partnerships.aiPartnershipAdvisor': 'Yapay Zeka Ortaklık Danışmanı',
    'partnerships.generateRecommendations': 'Önerileri Oluştur',
    'partnerships.overallStrategy': 'Genel Strateji',
    'partnerships.nextSteps': 'Sonraki Adımlar',
    'partnerships.opportunity': 'Fırsat',
    'partnerships.risk': 'Risk',
    'partnerships.priority': 'öncelik',
    'partnerships.initiateMOU': 'Protokol Başlat',
    'partnerships.message': 'Mesaj',
    'partnerships.noPartners': 'Henüz aktif ortaklık yok',
    'partnerships.noPartnersDesc': 'Ortak Keşfi sayfasında ortaklıkları keşfedin ve başlatın',
    'partnerships.sendMessage': 'Mesaj Gönder',
    'partnerships.subject': 'Konu',
    'partnerships.messageContent': 'Mesaj',
    'partnerships.send': 'Gönder',
    'partnerships.sent': 'Gönderildi',
    'partnerships.sentDesc': 'Mesaj başarıyla gönderildi',
    'partnerships.accept': 'Kabul Et',
    'partnerships.reject': 'Reddet',
    'partnerships.accepted': 'Kabul Edildi',
    'partnerships.rejected': 'Reddedildi',
    'partnerships.requestUpdated': 'Talep güncellendi:',
    'partnerships.noProjects': 'Proje bulunamadı',
    'partnerships.noRequests': 'Bekleyen talep yok',
    'partnerships.noMessages': 'Mesaj yok',
    'partnerships.from': 'Gönderen',
    'partnerships.to': 'Alıcı',
    'partnerships.date': 'Tarih',
    'partnerships.progress': 'İlerleme',
    'partnerships.budget': 'Bütçe',
    'partnerships.startDate': 'Başlangıç',
    'partnerships.endDate': 'Bitiş',
    
    // Partner Analytics
    'analytics.title': 'Ortak Analitiği',
    'analytics.subtitle': 'Tüm ortaklık anlaşmaları için kapsamlı analitik:',
    'analytics.partners': 'Ortaklar',
    'analytics.countries': 'Ülkeler',
    'analytics.exchanges': 'Değişimler',
    'analytics.funding': 'Fonlama',
    'analytics.publications': 'Yayınlar',
    'analytics.avgSatisfaction': 'Ort. Memnuniyet',
    'analytics.studentMobilityTrend': 'Öğrenci Hareketlilik Trendi',
    'analytics.incomingVsOutgoing': 'Akademik yıla göre gelen-giden karşılaştırması',
    'analytics.agreementTypeDist': 'Anlaşma Türü Dağılımı',
    'analytics.partnersByProgram': 'Program türüne göre ortaklar',
    'analytics.partnerDistByCountry': 'Ülkeye Göre Ortak Dağılımı',
    'analytics.studentsExchanged': 'öğrenci değişimi yapıldı',
    'analytics.partnersLabel': 'ortak',
    'analytics.partnerPerformance': 'Ortak Performans Özeti',
    'analytics.detailedMetrics': 'Her ortak üniversite için detaylı metrikler',
    'analytics.sortBy': 'Sırala',
    'analytics.filterByRegion': 'Bölgeye Göre Filtrele',
    'analytics.allRegions': 'Tüm Bölgeler',
    'analytics.totalStudents': 'Toplam Öğrenci',
    'analytics.satisfaction': 'Memnuniyet',
    'analytics.name': 'İsim',
    'analytics.university': 'Üniversite',
    'analytics.country': 'Ülke',
    'analytics.inOut': 'Gelen/Giden',
    'analytics.research': 'Araştırma',
    'analytics.noMobilityData': 'Hareketlilik verisi yok',
    'analytics.noProgramData': 'Program verisi yok',
    
    // Recruitment
    'recruitment.title': 'Öğrenci İşe Alım',
    'recruitment.subtitle': 'Uluslararası öğrenci işe alım takibi ve pazar analizi',
    'recruitment.selectUniversity': 'İşe alım verilerini görüntülemek için lütfen bir üniversite seçin.',
    'recruitment.editNumbers': 'Sayıları Düzenle',
    'recruitment.saved': 'Değişiklikler Kaydedildi',
    'recruitment.savedDesc': 'İşe alım verileri başarıyla güncellendi.',
    'recruitment.totalStudents': 'Toplam Öğrenci',
    'recruitment.countries': 'Ülkeler',
    'recruitment.acceptanceLetters': 'Kabul Mektupları',
    'recruitment.registered': 'Kayıtlı',
    'recruitment.frozen': 'Dondurulmuş',
    'recruitment.transfer': 'Transfer',
    'recruitment.deleted': 'Silinen',
    'recruitment.graduated': 'Mezun',
    'recruitment.byCountry': 'Ülkeye Göre',
    'recruitment.byAgency': 'Ajansa Göre',
    'recruitment.marketIntelligence': 'Pazar Analizi',
    'recruitment.studentsByCountry': 'Ülkeye Göre Öğrenciler',
    'recruitment.studentsByCountryDesc': 'Tüm işe alım metriklerinde ülkeye göre öğrenci sayılarını takip edin',
    'recruitment.studentsByAgency': 'Ajansa Göre Öğrenciler',
    'recruitment.studentsByAgencyDesc': 'Ortak ajanslar aracılığıyla öğrenci işe alımını takip edin',
    'recruitment.country': 'Ülke',
    'recruitment.agency': 'Ajans',
    'recruitment.students': 'Öğrenciler',
    'recruitment.mainCountries': 'Ana Ülkeler',
    'recruitment.commission': 'Komisyon',
    'recruitment.total': 'Toplam',
    'recruitment.avg': 'ort',
    'recruitment.agencies': 'ajans',
    'recruitment.analyzing': 'Analiz ediliyor...',
    'recruitment.analysisComplete': 'Analiz Tamamlandı',
    'recruitment.analysisCompleteDesc': 'Pazar analizi raporu başarıyla oluşturuldu.',
    'recruitment.analysisFailed': 'Analiz oluşturulamadı',
    'recruitment.analysisError': 'Analiz Hatası',
    'recruitment.generatingIntelligence': 'Pazar analizi oluşturuluyor...',
    'recruitment.totalApplications': 'Toplam Başvuru',
    'recruitment.avgConversion': 'Ort. Dönüşüm',
    'recruitment.marketsToScale': 'Büyütülecek Pazarlar',
    'recruitment.marketsToPause': 'Duraklatılacak Pazarlar',
    'recruitment.marketsToExit': 'Çıkılacak Pazarlar',
    'recruitment.fairs': 'Fuarlar',
    'recruitment.studentPlacement': 'Öğrenci Yerleştirme',
    'recruitment.nationalityDistribution': 'Uyruk Dağılımı',
    'recruitment.overview': 'Genel Bakış',
    'recruitment.year': 'Yıl',
    
    // Market Intelligence
    'intelligence.title': 'Pazar Analizi',
    'intelligence.subtitle': 'Yapay zeka destekli pazar analizi ve stratejik öneriler',
    'intelligence.generateAnalysis': 'Analiz Oluştur',
    'intelligence.regenerate': 'Yeniden Oluştur',
    'intelligence.recommendations': 'Yapay Zeka Önerileri',
    'intelligence.metrics': 'Pazar Metrikleri',
    'intelligence.confidence': 'Güven',
    'intelligence.risk': 'Risk Seviyesi',
    'intelligence.keyMetrics': 'Anahtar Metrikler',
    'intelligence.refreshAnalysis': 'Analizi Yenile',
    'intelligence.analysisComplete': 'Analiz Tamamlandı',
    'intelligence.analysisCompleteDesc': 'Pazar analizi raporu başarıyla oluşturuldu.',
    'intelligence.analysisFailed': 'Analiz oluşturulamadı',
    'intelligence.analysisError': 'Analiz Hatası',
    'intelligence.selectUniversity': 'Pazar analizini görüntülemek için lütfen bir üniversite seçin.',
    'intelligence.recruitmentMarketAnalysis': 'Yapay zeka destekli işe alım pazar analizi:',
    'intelligence.totalApplications': 'Toplam Başvuru',
    'intelligence.avgConversion': 'Ort. Dönüşüm',
    'intelligence.marketsToScale': 'Büyütülecek Pazarlar',
    'intelligence.marketsToPause': 'Duraklatılacak Pazarlar',
    'intelligence.marketsToExit': 'Çıkılacak Pazarlar',
    'intelligence.marketPerformance': 'Pazar Performans Metrikleri',
    'intelligence.detailedBreakdown': 'Ülkeye göre işe alım metriklerinin detaylı dağılımı',
    'intelligence.applications': 'Başvurular',
    'intelligence.offers': 'Teklifler',
    'intelligence.enrollments': 'Kayıtlar',
    'intelligence.conversionPct': 'Dönüşüm %',
    'intelligence.overOffering': 'Aşırı Teklif',
    'intelligence.wasteRatio': 'İsraf Oranı',
    'intelligence.agentPct': 'Ajans %',
    'intelligence.channelQuality': 'İşe Alım Kanal Kalitesi',
    'intelligence.highRiskMarkets': 'Yüksek Riskli Pazarlar',
    'intelligence.noHighRisk': 'Yüksek riskli pazar tespit edilmedi',
    'intelligence.generatingReport': 'Kapsamlı pazar analizi raporu oluşturuluyor...',
    'intelligence.conversionEfficiency': 'Dönüşüm Verimliliği',
    'intelligence.recruitmentQuality': 'İşe Alım Kalitesi',
    'intelligence.capacityAlignment': 'Kapasite Uyumu',
    
    // Documentation
    'docs.title': 'Öğrenci Belge Yönetimi',
    'docs.subtitle': 'Belge gereksinimleri, ülkeye özel kurallar ve öğrenci takibi',
    'docs.requirementsChecker': 'Gereksinim Kontrolü',
    'docs.countryRules': 'Ülke Kuralları',
    'docs.studentTracking': 'Öğrenci Takibi',
    'docs.specialCases': 'Özel Durumlar',
    'docs.selectUniversity': 'Belge yönetimini görüntülemek için lütfen bir üniversite seçin.',
    'docs.selectStudentProfile': 'Öğrenci Profilini Seçin',
    'docs.selectStudentDesc': 'Gerekli belgeleri görmek için öğrencinin durumunu seçin',
    'docs.studentStage': 'Öğrenci Aşaması',
    'docs.degreeLevel': 'Derece Seviyesi',
    'docs.countryOfOrigin': 'Menşe Ülkesi',
    'docs.educationSystem': 'Eğitim Sistemi',
    'docs.selectStage': 'Aşama seçin...',
    'docs.selectDegree': 'Derece seçin...',
    'docs.selectCountry': 'Ülke seçin...',
    'docs.selectEducation': 'Eğitim sistemi seçin...',
    'docs.getAIReqs': 'Yapay Zeka Gereksinimleri Al',
    'docs.requiredDocuments': 'Gerekli Belgeler',
    'docs.template': 'Şablon',
    'docs.required': 'Zorunlu',
    'docs.optional': 'İsteğe Bağlı',
    'docs.stamps': 'Gerekli Mühürler',
    'docs.howToObtain': 'Nasıl Elde Edilir',
    'docs.timeline': 'Süre',
    'docs.notes': 'Notlar',
    'docs.commonIssues': 'Yaygın Sorunlar',
    'docs.generalAdvice': 'Genel Tavsiye',
    'docs.estimatedTime': 'Tahmini Toplam Süre',
    'docs.countrySpecificRules': 'Ülkeye Özel Belge Kuralları',
    'docs.countryRulesDesc': 'Ülkeye göre belge gereksinimleri ve doğrulama kuralları',
    'docs.searchCountries': 'Ülke ara...',
    'docs.noRulesFound': 'Ülke kuralı bulunamadı',
    'docs.specificRequirements': 'Özel Gereksinimler',
    'docs.studentDocTracking': 'Öğrenci Belge Takibi',
    'docs.trackingDesc': 'Bireysel öğrencilerin belgelerini takip edin ve doğrulayın',
    'docs.addNewStudent': 'Yeni Öğrenci Ekle',
    'docs.searchStudents': 'Öğrenci ara...',
    'docs.allStatuses': 'Tüm Durumlar',
    'docs.inProgress': 'Devam Ediyor',
    'docs.complete': 'Tamamlandı',
    'docs.issues': 'Sorunlar',
    'docs.studentName': 'Öğrenci Adı',
    'docs.studentEmail': 'Öğrenci E-posta',
    'docs.studentId': 'Öğrenci No',
    'docs.createTracking': 'Takip Oluştur',
    'docs.noStudentsFound': 'Öğrenci bulunamadı',
    'docs.documentsVerified': 'belge doğrulandı',
    'docs.stage.newAdmission': 'Yeni Kayıt',
    'docs.stage.enrolled': 'Kayıtlı Öğrenci',
    'docs.stage.freeze': 'Kayıt Dondurma',
    'docs.stage.unfreeze': 'Kayıt Açma',
    'docs.stage.transferIn': 'Yatay Geçiş (Başka Üniversiteden)',
    'docs.stage.transferOut': 'Yatay Geçiş (Başka Üniversiteye)',
    'docs.degree.bachelors': 'Lisans',
    'docs.degree.masters': 'Yüksek Lisans',
    'docs.degree.phd': 'Doktora',
    'docs.edu.national': 'Ulusal Müfredat',
    'docs.edu.cambridge': 'Cambridge (O-Levels/A-Levels)',
    'docs.edu.ib': 'Uluslararası Bakalorya (IB)',
    'docs.edu.american': 'Amerikan Lisesi',
    'docs.edu.ged': 'GED',
    'docs.edu.cbse': 'CBSE (Hindistan)',
    'docs.edu.isc': 'ISC (Hindistan)',
    'docs.edu.waec': 'WAEC (Batı Afrika)',
    'docs.edu.neco': 'NECO (Nijerya)',
    'docs.edu.other': 'Diğer',
    
    // Special Cases
    'specialCases.title': 'Özel Durum Takibi',
    'specialCases.subtitle': 'Karmaşık öğrenci kayıt durumlarını takip edin ve yönetin',
    'specialCases.searchPlaceholder': 'İsim, numara veya bölüm ile ara...',
    'specialCases.allCategories': 'Tüm Kategoriler',
    'specialCases.allStatuses': 'Tüm Durumlar',
    'specialCases.credentialRecognition': 'Belge Tanınırlığı',
    'specialCases.academicFailure': 'Akademik Başarısızlık',
    'specialCases.warZone': 'Savaş Bölgesi / Çatışma',
    'specialCases.visaIssue': 'Vize Sorunu',
    'specialCases.other': 'Diğer',
    'specialCases.open': 'Açık',
    'specialCases.inProgress': 'İşlemde',
    'specialCases.pendingDocuments': 'Belge Bekleniyor',
    'specialCases.resolved': 'Çözüldü',
    'specialCases.escalated': 'Üst Makama İletildi',
    'specialCases.activeCases': 'aktif vaka',
    'specialCases.caseDetails': 'Vaka Detayları',
    'specialCases.progressTimeline': 'İlerleme Zaman Çizelgesi',
    'specialCases.noCasesFound': 'Kriterlerinize uyan vaka bulunamadı',
    'specialCases.department': 'Bölüm',
    'specialCases.enrollmentYear': 'Kayıt Yılı',
    'specialCases.nationality': 'Uyruk',
    'specialCases.issue': 'Sorun',
    'specialCases.requiredAction': 'Gerekli Eylem',
    
    // Auth
    'auth.title': 'IRIS',
    'auth.subtitle': 'Uluslararası İlişkiler Akıllı Sistemi',
    'auth.login': 'Giriş Yap',
    'auth.signup': 'Kayıt Ol',
    'auth.email': 'E-posta',
    'auth.password': 'Şifre',
    'auth.confirmPassword': 'Şifre Tekrar',
    'auth.fullName': 'Ad Soyad',
    'auth.loginButton': 'Giriş Yap',
    'auth.signupButton': 'Hesap Oluştur',
    'auth.loggingIn': 'Giriş yapılıyor...',
    'auth.signingUp': 'Hesap oluşturuluyor...',
    'auth.welcomeBack': 'Tekrar hoş geldiniz',
    'auth.signInToContinue': 'IRIS\'e devam etmek için giriş yapın',
    'auth.createAccount': 'Hesabınızı oluşturun',
    'auth.getStarted': 'IRIS ile başlayın',
    'auth.checkEmail': 'E-postanızı kontrol edin',
    'auth.verifyEmail': 'Devam etmek için e-posta adresinizi doğrulayın.',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.save': 'Kaydet',
    'common.cancel': 'İptal',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.add': 'Ekle',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.refresh': 'Yenile',
    'common.generate': 'Oluştur',
    'common.download': 'İndir',
    'common.upload': 'Yükle',
    'common.submit': 'Gönder',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.completed': 'Tamamlandı',
    'common.pending': 'Beklemede',
    'common.active': 'Aktif',
    'common.inactive': 'Pasif',
    'common.draft': 'Taslak',
    'common.approved': 'Onaylandı',
    'common.rejected': 'Reddedildi',
    'common.students': 'öğrenci',
    'common.records': 'kayıt',
    'common.unknown': 'Bilinmiyor',
    'common.close': 'Kapat',
    'common.confirm': 'Onayla',
    'common.yes': 'Evet',
    'common.no': 'Hayır',
    'common.noData': 'Veri mevcut değil',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.actions': 'İşlemler',
    'common.status': 'Durum',
    'common.type': 'Tür',
    'common.region': 'Bölge',
    'common.date': 'Tarih',
  },
  de: {
    // German translations - keeping existing ones, falling back to English for new keys
    'header.viewingAs': 'Anzeige als:',
    'header.selectUniversity': 'Universität auswählen',
    'header.loading': 'Laden...',
    'header.turkishUniversities': 'Türkische Universitäten',
    'header.internationalUniversities': 'Internationale Universitäten',
    'header.signOut': 'Abmelden',
    'header.language': 'Sprache',
    'nav.dashboard': 'Dashboard',
    'nav.profile': 'Profil',
    'nav.partners': 'Partner',
    'nav.mobility': 'Mobilität',
    'nav.mou': 'MOU',
    'nav.partnerships': 'Partnerschaften',
    'nav.intelligence': 'Marktanalyse',
    'nav.partnerAnalytics': 'Analytik',
    'nav.documentation': 'Dokumentation',
    'common.loading': 'Laden...',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.refresh': 'Aktualisieren',
    'common.students': 'Studierende',
    'common.records': 'Einträge',
    'common.unknown': 'Unbekannt',
  },
  ar: {
    // Arabic translations - keeping existing ones, falling back to English for new keys
    'header.viewingAs': 'العرض كـ:',
    'header.selectUniversity': 'اختر الجامعة',
    'header.loading': 'جاري التحميل...',
    'header.turkishUniversities': 'الجامعات التركية',
    'header.internationalUniversities': 'الجامعات الدولية',
    'header.signOut': 'تسجيل الخروج',
    'header.language': 'اللغة',
    'nav.dashboard': 'لوحة التحكم',
    'nav.profile': 'الملف الشخصي',
    'nav.partners': 'الشركاء',
    'nav.mobility': 'التنقل',
    'nav.mou': 'مذكرة التفاهم',
    'nav.partnerships': 'الشراكات',
    'nav.intelligence': 'تحليل السوق',
    'nav.partnerAnalytics': 'التحليلات',
    'nav.documentation': 'إدارة المستندات',
    'common.loading': 'جاري التحميل...',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.refresh': 'تحديث',
    'common.students': 'طالب',
    'common.records': 'سجل',
    'common.unknown': 'غير معروف',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  tr: 'Türkçe',
  de: 'Deutsch',
  ar: 'العربية',
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('iris-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('iris-language', lang);
    // Update document direction for RTL languages
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    // Set initial direction
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, []);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  const dir = language === 'ar' ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export { languageNames };
