import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ListChecks, ArrowRight, CheckCircle2 } from 'lucide-react';
import { useUniversity } from '@/contexts/UniversityContext';
import { computeActionItems, type ActionItem } from '@/lib/automation';

const SEV_STYLE: Record<ActionItem['severity'], string> = {
  high: 'bg-red-100 text-red-800 border-red-300',
  medium: 'bg-yellow-100 text-yellow-800 border-yellow-300',
  low: 'bg-slate-100 text-slate-700 border-slate-300',
};

/** IRIS Autopilot: the automatically generated agenda, recomputed from live
 *  data on every dashboard visit. */
export function AgendaCard() {
  const { selectedUniversity } = useUniversity();
  const [items, setItems] = useState<ActionItem[] | null>(null);

  useEffect(() => {
    let cancelled = false;
    if (!selectedUniversity) return;
    computeActionItems(selectedUniversity.id).then((res) => {
      if (!cancelled) setItems(res);
    });
    return () => {
      cancelled = true;
    };
  }, [selectedUniversity]);

  return (
    <Card className="lg:col-span-3">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-base">
          <ListChecks className="h-5 w-5 text-primary" /> Automated agenda
        </CardTitle>
        <CardDescription>
          Generated by IRIS from your live data — renewals, follow-ups and cadence, no manual tracking.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {items === null ? (
          <p className="text-sm text-muted-foreground">Analyzing…</p>
        ) : items.length === 0 ? (
          <p className="flex items-center gap-2 text-sm text-muted-foreground">
            <CheckCircle2 className="h-4 w-4 text-green-600" /> Nothing needs attention — all
            agreements current, requests answered, assessment fresh.
          </p>
        ) : (
          <div className="grid gap-2 md:grid-cols-2">
            {items.map((it) => (
              <Link
                key={it.id}
                to={it.route}
                className="flex items-start justify-between gap-3 rounded-lg border p-3 text-sm transition-colors hover:bg-secondary"
              >
                <div className="min-w-0 space-y-1">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className={`h-4 px-1 text-[10px] ${SEV_STYLE[it.severity]}`}>
                      {it.severity.toUpperCase()}
                    </Badge>
                    {it.dueLabel && <span className="text-[10px] text-muted-foreground">{it.dueLabel}</span>}
                  </div>
                  <p className="font-medium leading-snug">{it.title}</p>
                  <p className="text-xs text-muted-foreground leading-snug">{it.detail}</p>
                </div>
                <ArrowRight className="mt-1 h-4 w-4 shrink-0 text-muted-foreground" />
              </Link>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
